package Modelo.hibernate;
// Generated 30/05/2018 02:43:43 PM by Hibernate Tools 4.3.1



/**
 * Fila generated by hbm2java
 */
public class Fila  implements java.io.Serializable {


     private FilaId id;
     private int duracion;

    public Fila() {
    }

    public Fila(FilaId id, int duracion) {
       this.id = id;
       this.duracion = duracion;
    }
   
    public FilaId getId() {
        return this.id;
    }
    
    public void setId(FilaId id) {
        this.id = id;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }




}


