package Modelo.hibernate;
// Generated 30/05/2018 02:43:43 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;




/**
 * Perfiles generated by hbm2java
 */

@Entity
@XmlRootElement
public class Perfiles  implements java.io.Serializable {

     @Id
     private int id;
     private String perfil;

    public Perfiles() {
    }

    public Perfiles(int id, String perfil) {
       this.id = id;
       this.perfil = perfil;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }




}


