package Modelo.hibernate;
// Generated 30/05/2018 02:43:43 PM by Hibernate Tools 4.3.1



/**
 * Tarea generated by hbm2java
 */
public class Tarea  implements java.io.Serializable {


     private int id;
     private String nombre;

    public Tarea() {
    }

    public Tarea(int id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


