package Modelo.app;
// Generated 29/05/2018 06:39:56 PM by Hibernate Tools 4.3.1


import java.sql.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private Date fechaNacimiento;
     private boolean activo;

    public Usuarios() {
    }

    public Usuarios(int id, Date fechaNacimiento, boolean activo) {
       this.id = id;
       this.fechaNacimiento = fechaNacimiento;
       this.activo = activo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


